name: 'Deploy to Cloud Run from Source'

on:
  push:
    branches:
      - '"master"'

env:
  PROJECT_ID: 'typemonkey'
  REGION: 'asia-southeast2'
  SERVICE: 'typemonkey'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/26375814418/locations/global/workloadIdentityPools/github'

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          source: './'
          flags: '--allow-unauthenticated' '--concurrency=10' '--max=2' '--min=0'

      - name: 'Show output'
        run: |-
          echo ${{ steps.deploy.outputs.url }}
